### ISSUE TITLE
flake: TestEnterpriseAuditLogs/IncludeOrganization

### ISSUE THREAD

**Issue by Kira-Pilot** [coder/internal#111] opened 2024-10-16 18:58 UTC
`TestEnterpriseAuditLogs/IncludeOrganization` is flaking. We should investigate and make sure this test is stable going forward.

Logs are available [here](https://github.com/coder/coder/actions/runs/10966355130/job/30454182873).

**Comment by code-asher** [comment] 2024-10-18 22:22
I started looking at this, it seems like a race between setting the license and creating an organization, and it seems like it could potentially affect any test that uses licenses but I have not reproduced or found a root cause yet.

**Comment by Kira-Pilot** [comment] 2024-10-18 23:21
Passing on to you @Emyrk, do you mind taking a look?

**Comment by Emyrk** [comment] 2024-10-21 12:56
Adding a license looks like a blocking operation, and AddLicense calls the update (which the logs indicate also happens async). I will try and find time this week


```
    t.go:99: 2024-09-20 21:19:39.685 [debu]  coderd: POST  host=localhost:64134  path=/api/v2/licenses  proto=HTTP/1.1  remote_addr=127.0.0.1  start="2024-09-20T21:19:39.683314Z"  took=1.919459ms  status_code=201  latency_ms=1  request_id=8a1c4a16-0597-44c5-a5d9-d2448ca34bbd
    t.go:99: 2024-09-20 21:19:39.685 [debu]  coderd: synced licensed entitlements
    t.go:99: 2024-09-20 21:19:39.685 [debu]  coderd: got pubsub update
    t.go:99: 2024-09-20 21:19:39.685 [debu]  coderd: syncing licensed entitlements
    t.go:99: 2024-09-20 21:19:39.685 [debu]  coderd: POST  host=localhost:64134  path=/api/v2/organizations  proto=HTTP/1.1  remote_addr=127.0.0.1  start="2024-09-20T21:19:39.685492Z"  took=470.084µs  status_code=403  latency_ms=0  request_id=fca49efe-bbcc-4278-a575-a70eca1b3ed0
    audit_test.go:43: 
        	Error Trace:	/Users/runner/work/coder/coder/enterprise/coderd/audit_test.go:43
        	Error:      	Received unexpected error:
        	            	POST http://localhost:64134/api/v2/organizations: unexpected status code 403: Multiple Organizations is a Premium feature. Contact sales!
        	Test:       	TestEnterpriseAuditLogs/IncludeOrganization
    t.go:99: 2024-09-20 21:19:39.686 [debu]  coderd: synced licensed entitlements
```

**Comment by Emyrk** [comment] 2024-10-29 19:28
I found the issue, but it was fixed by https://github.com/coder/coder/pull/14974

**Closed as completed by Emyrk** 2024-10-29 19:28 UTC
Labels: flake
